# Generated by Django 4.2 on 2023-01-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='post.post'),
        ),
    ]
