# Generated by Django 4.2 on 2023-01-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_attachment_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='post_id',
        ),
    ]
