# Generated by Django 4.1.5 on 2023-01-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_created_by_user_updated_by_and_more'),
        ('post', '0004_remove_attachment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='user.user'),
        ),
    ]
