# Generated by Django 4.2 on 2023-01-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userplatform', '0002_platform_created_by_platform_created_on_and_more'),
        ('user', '0002_user_created_by_user_updated_by_and_more'),
        ('credential', '0002_credential_created_by_credential_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='platform',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='userplatform.platform'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='user.user'),
        ),
    ]
