# Generated by Django 4.1.5 on 2023-01-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0003_alter_credential_platform_alter_credential_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='updated_by',
        ),
    ]
