# Generated by Django 4.1.4 on 2023-01-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('mobile_number', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('platform_type_id', models.PositiveIntegerField()),
                ('urls', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('mobile_number', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
