# Generated by Django 4.1.4 on 2023-01-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='credential',
            name='mobile_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
