# Generated by Django 4.1.4 on 2023-01-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_credential_is_active_alter_credential_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='user_id',
        ),
        migrations.AddField(
            model_name='credential',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='automation.user'),
        ),
    ]
