# Generated by Django 4.1.4 on 2023-01-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_remove_credential_user_id_credential_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
