# Generated by Django 4.2 on 2023-01-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
