# Generated by Django 4.1.5 on 2023-01-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_role_created_on_role_updated_on_alter_role_name'),
        ('user', '0002_user_created_by_user_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to='role.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_user', to='role.role'),
        ),
    ]
