# Generated by Django 4.1.5 on 2023-01-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_created_by_alter_user_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_by',
        ),
    ]
