# Generated by Django 4.2 on 2023-01-12 04:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='created_by',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to='userplatform.platform'),
        ),
        migrations.AddField(
            model_name='platform',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='updated_by',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_user', to='userplatform.platform'),
        ),
        migrations.AddField(
            model_name='platform',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
