# Generated by Django 4.1.5 on 2023-01-25 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_created_by_alter_user_updated_by'),
        ('userplatform', '0002_platform_created_by_platform_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to='user.user'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_user', to='user.user'),
        ),
    ]
